application: meyjarverdandi
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /static
  static_dir: static

- url: /cron/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
  login: required


libraries:
- name: lxml
  version: latest
